apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dotnet-actions-artifactory-140425 
  janus-idp.io/tekton: dotnet-actions-artifactory-140425
  backstage.io/kubernetes-id: dotnet-actions-artifactory-140425
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-actions-artifactory-140425
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml