apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet-actions-artifactory-140425
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-actions-artifactory-140425 
  name: dotnet-actions-artifactory-140425
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet-actions-artifactory-140425 
